sudo: false
os:
  - linux
language: cpp
compiler: clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - zlib1g-dev
    - libbz2-dev 
    - libsnappy-dev
    - clang-3.6

env: COMPILER=clang++-3.6

# Lousy hack to disable use and testing of fallocate, which doesn't behave quite
# as EnvPosixTest::AllocateTest expects within the Travis OpenVZ environment.
script: CXX=$COMPILER OPT=-DTRAVIS V=1 make unity && make clean && CXX=$COMPILER OPT=-DTRAVIS V=1 make db_test && ./db_test && CXX=$COMPILER OPT=-DTRAVIS V=1 make clean jclean rocksdbjava jtest
notifications:
    email: false
    webhooks:
      - https://buildtimetrend.herokuapp.com/travis
