version: 1.0.{build}
before_build:
- md %APPVEYOR_BUILD_FOLDER%\build
- cd %APPVEYOR_BUILD_FOLDER%\build
- cmake -G "Visual Studio 12 Win64" -DOPTDBG=1 ..
- cd ..
build:
  project: build\ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal
test:
test_script:
- ps: build_tools\run_ci_db_test.ps1
